### ISSUE TITLE
Problems with IEntryPoint

### ISSUE THREAD

**Issue by erotundo** [falahati/NetworkAdapterSelector#13]
Hi!

I try to run the app with latest version of EasyHook and i got this message

The given user library does not export a proper Run(EasyHook.InjectionLoader+REMOTE_ENTRY_INFO, System.String) method in the 'EasyHook.IEntryPoint' interface.

What i can do with this? Need and a class or interface implementation?

**Comment by falahati** [comment]
Hey, sorry about that. It's the master and changes might not be necessarily working.
This fix here is to edit the `Guest.cs` file and replace these lines:

```C#
        public void Run(
            RemoteHooking.IContext inContext,
            string injectionAddress,
            string adapterId,
            int injectionDelay,
            bool isDebug)
```
with
```C#
        public void Run(
            RemoteHooking.IContext inContext,
            string adapterId,
            string injectionAddress,
            int injectionDelay,
            bool changeWindowTitle,
            bool isDebug)
```

**Comment by erotundo** [comment]
Perfect! sorry for answer late, works with your suggestion.
