### ISSUE TITLE
Can i bind adapter without using shell extension

### ISSUE THREAD

**Issue by Lemonpartyy** [falahati/NetworkAdapterSelector#3]
Hello, can some1 advice how can i bind my adapter, using shortcut (like forcebindip)
Or give me please example

**Comment by falahati** [comment]
Command Line Parameters:

- `-n` `--network`: Identification string of the network adapter to bind.
- `-e` `--execute`: Address of the executable find to start.
- `-c` `--args`: Arguments to be sent to the executable while starting.
- `-a` `--attach`: PID of the process to attach.
- `-t` `--delay`: Delay in milliseconds before trying to inject the code.
- `-d `--debug`: Debug mode creates a log file in temp directory logging all the activities of the injected code. (Boolean)

Network identification is the network GUID. To get those you can run the following command in the CMD:
```
net start "Wired AutoConfig"
net start "WLAN AutoConfig"
netsh lan show interfaces
netsh wlan show interfaces
```

Or you can use the registry and read them from here:
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsNT\CurrentVersion\NetworkCards
```

Example for attaching to an already running process: (PID `1234`)
```
NetworkAdapterSelector.Hook.exe --network "{ABCDEFGH-0000-0000-0000-000000000000}" --attach 1234
```

Example for starting a new application:
```
NetworkAdapterSelector.Hook.exe --network "{ABCDEFGH-0000-0000-0000-000000000000}" --execute "C:\Windows\System32\notepad.exe" -t 1000
```

**Comment by Lemonpartyy** [comment]
Thank you very much for this constructive post

**Comment by Lemonpartyy** [comment]
May i ask you again, if i do not discract you
NetworkAdapterSelector.Hook.exe --network "{ABCDEFGH-0000-0000-0000-000000000000}" --execute "C:\Windows\System32\notepad.exe" --delay 1000 -c " -width 800 -height 600 "
This is the correct use of args option?

**Comment by falahati** [comment]
Yes, this should work, do you have any problem with it?

**Comment by Lemonpartyy** [comment]
My apologies, it's work perfect, i was a bit inconsiderate, thank you.
