### ISSUE TITLE
Hard CPU demands

### ISSUE THREAD

**Issue by Lemonpartyy** [falahati/NetworkAdapterSelector#4]
In the last 20-30 tests, I found a very high CPU intake, executables which take small cpu usage(1-2%) after injecting dll start consuming a lot more resources (10-12% for me) It's hard to work with 3-4 NetworkAdapterSelectors running at the same time
Windows 8.1 64-bit
If you can give me any advice, i will be very happy,

**Comment by falahati** [comment]
Hey,

Can you name the application or at least its functionality?

**Comment by falahati** [comment]
Closed due to inactivity.
