### ISSUE TITLE
Two or more copies of same process

### ISSUE THREAD

**Issue by uzhas-sovka** [falahati/NetworkAdapterSelector#5]
Hi, Falahati, thanks a lot for your blog post, it's extremely helpful.

This is not an issue, maybe a question.

1) My config is two TAP adapters and a single physical card. 

2) I run OpenVPN + config file and obtain two separate VPN connections, they are visible in Windows routes. Names are VPN0 and VPN1. 

3) Both connections alive and working.

4) I choose [Run As] VPN0 from shell extension, launch FF, and it perfectly gets me expected IP address (Russia, for example).

5) If I choose [Run As] VPN1 and launch second FF copy, it will still get me Russia but not expected Germany.

6) If first server to run will be VPN1, then it'll be Germany IP, but if I ran VPN0 after it. it will also get me Germany.

So my aim is to have two (or more) running simultaneously FFs, first connecting through VPN0, second through VPN1. At first I decided to install second Firefox to a different location and rename executable, but to no avail.

Please help. You don't have to change anything in your program. it obviously works well. But maybe I have to change it to meet my strange requirements. Thank you!

**Comment by falahati** [comment]
Hey @uzhas-sovka,
Based on your description and knowing how this program works, I suspect that the problem comes from the OpenVPN itself and not your network connections. Are you sure that at any given time, when both VPN connections are active, you have correct access to both VPN networks? You can confirm this with modifying Windows's Routing table and default gateway.

**Comment by uzhas-sovka** [comment]
Hi, Falahati, thanks for prompt reply. Here is my config to prove independent work of two Openvpn services (I launch two services, no GUI).

![new-1](https://user-images.githubusercontent.com/4897106/32069465-eefcc5fa-ba91-11e7-9a76-0e7fe6fd67ee.png)

The idea is obvious: add routes with direct IP addresses of IP checking cites. And it works as expected, even within "single" Chrome with two tabs. In one tab I'm in Germany, in other - in France.

Truly speaking this route config is not done by Openvpn itself. I created C# program to trace new lines added by OpenVPN during launch .ovpn files and filter out some obviously redundant lines.

And during my experiments to prove OpenVPN functioning I suddenly remembered that two FF launches may lead to one process in memory. Maybe this is the case?

And another question, maybe stupid, because I worked with dlls only once 3 years ago. Does your injection works "system-wide", or for single process?

**Comment by falahati** [comment]
If you have verified your configuration, I can not see an immediate reason for the application to not work. I may need to reproduce the situation by starting multiple OpenVPN connections.

> And during my experiments to prove OpenVPN functioning I suddenly remembered that two FF launches may lead to one process in memory. Maybe this is the case?

Sure, this might be the root of the issue. You see, this program tries to inject it's DLL to the newly started process; however, FF and Chrome, both, will send an IPC request to the already running instance and then close the new process right after that, and as the result, the injection will also vanish. Therefore you always end up with the first instance of the application. In case of chrome it is more complicated as it likes to divide itself to multiple processes, but still, they behave similarly with respect to the subject of this discussion.

To be able to truly run two versions of Firefox, you need to select another profile for the newly executed version of it. Just google the phrase "How to open a new instance of Firefox".

> Does your injection work "system-wide", or for single process?

It tries to stick itself to the process you requested to control and also it's child processes. This behavior minimizes the risk of any crash or damage to one application.

**Comment by uzhas-sovka** [comment]
"How to open a new instance of Firefox"
I've just did it. My goal is to use your ideas to run multiple Webdriver-driven FF instances. And Webdriver (i.e. Geckodriver these days) already launches truly independent FF sessions with separate profiles.

But I still haven't succeed. Another experimental session is:

1) Add to FF shortcut options "-P -no-remote".
2) Run shortcut two times via shell extension and via ordinary clicking.

Firefox thus is launched as two independent processes, but it seems that injection still is done once. This is visible in startup menu, when you choose profile to launch.
![new-2](https://user-images.githubusercontent.com/4897106/32076257-f9dac8f8-baa7-11e7-807d-ded4768972ec.png)

When you try to launch FF via shell extension second time, profile menu doesn't appear at all. It's strange, because during two "normal" launches the menu is shown two times, as expected.

Is there any way to attach injector to already running process?.. It seems that I glanced over something in your blog, or maybe I'm dreaming...

**Comment by falahati** [comment]
Yeah, check the project's readme.

**Comment by uzhas-sovka** [comment]
Another unexpected twist. I'm trying to attach injector to running process. And got error

System.Exception: Selected network id is invalid or the selected interface is not functional. at NetworkAdapterSelector.Hook.Program.Main()

Triple-checked GUIDs and then went to registry. TAP "cards" are not listed there, only physical cards.

**Comment by uzhas-sovka** [comment]
It seems I have to change this block

if (!NetworkInterface.GetAllNetworkInterfaces()
                    .Any(
                        @interface =>
                            @interface.Id.Equals(networkId, StringComparison.CurrentCultureIgnoreCase) &&
                            @interface.SupportsMulticast &&
                            @interface.OperationalStatus == OperationalStatus.Up))
                {
                    throw new Exception("Selected network id is invalid or the selected interface is not functional.");
}

**Comment by uzhas-sovka** [comment]
Strange, but this snippet works perfect. Moreover, I use NetworkInterface.GetAllNetworkInterfaces myself during route management...

**Comment by falahati** [comment]
Yeah, the registry is usually outdated or missing virtual drivers. Did you manage to solve the problem with the "Selected network id is invalid or the selected interface is not functional." error message? Read the ID directly from the `NetworkInterface.GetAllNetworkInterfaces()`.

**Comment by uzhas-sovka** [comment]
It's strange, because I build route structure using this method BEFORE I make injection... Without errors...

**Comment by falahati** [comment]
> When you try to launch FF via shell extension second time, profile menu doesn't appear at all. It's strange, because during two "normal" launches the menu is shown two times, as expected.

Ok, it seems that the shell script, when working with shortcuts, don't actually send the arguments used in the shortcut to the application. So its a bug in the shell extension. However, still, you should be able to use the executable file directly.

**Comment by uzhas-sovka** [comment]
It's OK with attaching cards, my fault. I missed space in command line after adapter ID and PID.

Now testing sequence is following:
1) Launch FF via Geckodriver and get FF PID.
2) Launch injector.

And it seems that injection is done only once in no specific order,
![new-3](https://user-images.githubusercontent.com/4897106/32111837-5cac52de-bb44-11e7-9069-954b4cefdc63.png)
![new-1](https://user-images.githubusercontent.com/4897106/32111847-62311d34-bb44-11e7-8a95-ea773d4974dd.png)

**Comment by uzhas-sovka** [comment]
I managed to inject into two FFs, but finally got

System.TimeoutException: Unable to wait for injection completion.

Timeouts between FF launch and injection don't help.

**Comment by uzhas-sovka** [comment]
Changed browser.tabs.remote.autostart.2 to make FF start as one process. Results are not clear, one of openvpns always shuts down without known reason...

**Comment by uzhas-sovka** [comment]
Done!
![new-1](https://user-images.githubusercontent.com/4897106/32117530-657465e2-bb57-11e7-9c86-2ad7967df08c.png)

**Comment by uzhas-sovka** [comment]
Falahati, thank you very much. It seems that you are the only person in the world who is interested in problem so extremely important for me. I understand that such words are not suitable for Github topics, but you literally saved my ass with this program.

At first I sequentially turned openvpn on and off (8 seconds per cycle), then I tried to change route table on the fly keeping many openvpns running (20 seconds per cycle, who would have think!) and finally your program to make things a way faster, because now I can run sessions in parallel...

**Comment by falahati** [comment]
> System.TimeoutException: Unable to wait for injection completion.

Add a `Thread.Sleep(1000)` before running `NetworkAdapterSelector.Hook.exe` with PID and it should work. Alternately, you can do this:
`"C:\Program Files (x86)\Network Adapter Selector\NetworkAdapterSelector.Hook.exe" -n "{7BB5DF0E-6535-4994-A3FF-C1D9A1979665}" -e "C:\Program Files (x86)\Mozilla Firefox\firefox.exe" -c "\"""-p default -no-remote\"""" -t 1000`

Change the network id from `7BB5DF0E-6535-4994-A3FF-C1D9A1979665` to the one you want and change the profile from `default` to a unique profile per process. Should work.

> Falahati, thank you very much. It seems that you are the only person in the world who is interested in problem so extremely important to me. I understand that such words are not suitable for Github topics, but you literally saved my ass with this program.
To be honest I didn't do much. But you are welcome :)

> At first I sequentially turned openvpn on and off (8 seconds per cycle), then I tried to change route table on the fly keeping many openvpns running (20 seconds per cycle, who would have think!) and finally your program to make things a way faster, because now I can run sessions in parallel...

What are you trying to achieve? Just for the record, I don't know @uzhas-sovka and have no affiliation with what he is doing. xD

**Comment by uzhas-sovka** [comment]
Thank you for additional command line options... I'm writing a trade bot, sort of Ebay loader, but not for Ebay.
