### ISSUE TITLE
impossible to uninstall 

### ISSUE THREAD

**Issue by shinobize** [falahati/NetworkAdapterSelector#6]
Since a week i can use an other network , im trying to uninstall but it show me error : 

![image](https://user-images.githubusercontent.com/15818806/32278202-38cdc1de-bf15-11e7-8892-7024bbcce79e.png)

**Comment by woneob** [comment]
Same issue. I can't uninstall (windows 10)

**Comment by falahati** [comment]
This should fix your problems:
https://github.com/falahati/NetworkAdapterSelector/releases/tag/v1.1.0.0-dev

Run it only once and it should be able to remove the latest release. Running it again results in an installation. It should warn you about an older installation if you have the app already in place.
