### ISSUE TITLE
ipv6 not working

### ISSUE THREAD

**Issue by jasonwm** [falahati/NetworkAdapterSelector#7]
My network is forced to ipv6,  if I disable ipv6, then network will down , it reports has no internet access right.

but in ipv6, this networkAdapterSelector will not work .

the BindSocket will go into default
default:
                    return true;

**Comment by falahati** [comment]
At this moment, ipv6 is not supported,
However, I just pushed some changes that might make it work with ipv6, but I am sure and I didn't have the time to even test it with ipv4 yet. You can try it at your own risk.

https://github.com/falahati/NetworkAdapterSelector/releases/tag/v1.1.0.0-dev
