### ISSUE TITLE
Doesn't work with FF 54

### ISSUE THREAD

**Issue by uzhas-sovka** [falahati/NetworkAdapterSelector#8]
Hi, Falahati,
thanks a lot for this wonderful software, though a year ago after successful launch of 5 FF copies with 5 TAP adapters I decided to move to a separate standalone notebooks with one VPN per each, but that's another story.

It seems that NAS (1.0) works up to FF 53. FF 54 just clears URL on address line and stops. I checked Wireshark dump but did not find any valuable info, maybe due to lack of knowledge. Several requests go out and stop. "Malformed TCP".

I can stick with FF53, it's quite fresh version, but maybe there is some simple solution. Thank you!

**Comment by falahati** [comment]
Hey @uzhas-sovka,

It seems Firefox is now using some sort of memory or debugger protection. Therefore, I changed the code to inject before any of Firefox's codes get executed.

These changes are now live with the latest commits. However, I am now waiting for some problems with the SharpShell project to get solved before releasing a new version.

**Comment by uzhas-sovka** [comment]
Thanks. Can I compile only hook part? It seems to be isolated from the other parts, and I need only injecting into running process.

**Comment by falahati** [comment]
You probably can. Try it and get back to me with the result, please.

**Comment by uzhas-sovka** [comment]
First attempt, no success, Visual studio 2017 fails to load EasyHook, nuget hangs. But I think I'll manage somehow to get it right.

**Comment by falahati** [comment]
NuGet is probably downloading EasyHook or something. In any case, I just compiled and uploaded this from `master` for you to test; just copy and overwrite files to the program's installation folder.

[NetworkAdapterSelector.Hook.zip](https://github.com/falahati/NetworkAdapterSelector/files/2726292/NetworkAdapterSelector.Hook.zip)

**Comment by uzhas-sovka** [comment]
53 FF resets URL and stops, injector says SUCCESS.

Falahati, you may proceed with your own agenda with this program, no need to handle my requests. My configuration, as I may understand from your post in another thread, is unstable: I always run (maybe two copies) FF with Selenium beforehand, and inject NAS afterwards.

**Comment by falahati** [comment]
In any case, you can debug the application to see how things are going and why your request gets rejected. 

To do so, run the `NetworkAdapterSelector.Hook.exe` manually using command lines (`-e "FIREFOX ADDRESS" -n {NETWORKID} -d`) and then go to the Windows's temp folder (%temp%) and find the latest file created with this name pattern: `NetworkAdapterSelector-firefox[XXXXX].log` and post it here or read it.

When I created this tool I had like two network connection to two different modems and used this tool to switch my apps between them. However, I later got a load balancer and never used this anymore. So last time I tried it was to see if I can still access my real internet connection when connected to a VPN just like you are trying to do now. Didn't had much success tho. It seems when using TAP Adapter with some VPN providers, I get "Host Unreachable" when trying to force bind (with or without this tool, even writing my own program) and some providers even actively block your access to the main connection (NordVPN, for example, has a firewall service that rejects request with an `Access Denied` response).

My only success was with Kario. So it might be that in your case too. Reading logs might help you see the real reason why requests get rejected.

**Comment by uzhas-sovka** [comment]
I have a difficult choice: either trying to understand the inner working of EasyHook and your program, or to build stack of 50-dollar used notebooks with Pentium M processor and 2 GB RAM, each notebook for one running browser and one VPN connection.

The latter option seems to be more reliable, but my origins from DOS assembly language push me back to your program again and again.

Thank you very much anyway.

**Comment by falahati** [comment]
It's alright; if you had any other problem or question; feel free to open this issue again.
